name: Build documentation with Sphinx

on:
  push:
    branches:
      - master
  release:
    types: [published]


jobs:
  build:
    name: Build Sphinx documenation in a Docker container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current ref
      uses: actions/checkout@v2
      with:
        path: repository

    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: pages

    - name: Sphinx Docker build
      uses: g5t/sphinxer
      with:
        source_dir: repository
        pages_dir: pages
        is_release: ${{ constains(github.event_name, 'release' )}}
        create_readme: true
  
