name: Run Pytest

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Update Python pip and required packages
      run: |
        python -m pip install --upgrade pip pytest brille euphonic

    - name: Run Pytest
      run: |
        python -m pytest
